name: systemaops

services:
  dashboard:
    image: systemaops
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systemaops
    ports:
      - "5173:80"
    restart: always
